# Generated by Django 5.2.5 on 2025-08-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbuseEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("malicious", "Malicious"),
                            ("international_number", "International Number"),
                            ("usa_number", "Usa Number"),
                            ("voip_number", "Voip Number"),
                            ("blocked_number_retry", "Blocked Number Retry"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("behavioral", "Behavioral"),
                            ("system", "System"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("severity_weight", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RiskProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("flagged", "Flagged"),
                            ("rate_limited", "Rate Limited"),
                            ("soft_blocked", "Soft Blocked"),
                            ("hard_blocked", "Hard Blocked"),
                            ("banned", "Banned"),
                        ],
                        max_length=24,
                    ),
                ),
                ("risk_score", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AbuseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("preflight", "Preflight"),
                            ("post_analysis", "Post Analysis"),
                        ],
                        max_length=24,
                    ),
                ),
                ("message_content", models.TextField(blank=True, null=True)),
                ("sms_id", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gatekeeper.abuseeventtype",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gatekeeper.riskprofile",
                    ),
                ),
            ],
        ),
    ]
