# Generated by Django 5.2.5 on 2025-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatekeeper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abuseeventtype",
            name="severity_weight",
        ),
        migrations.RemoveField(
            model_name="riskprofile",
            name="risk_score",
        ),
        migrations.AddField(
            model_name="abuseeventtype",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("blocked", "Blocked"),
                ],
                default="low",
                max_length=24,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="abuseeventtype",
            name="name",
            field=models.CharField(
                choices=[
                    ("malicious", "Malicious"),
                    ("international_number", "International Number"),
                    ("usa_number", "Usa Number"),
                    ("voip_number", "Voip Number"),
                    ("frustrated_user", "Frustrated User"),
                    ("commercial_spam", "Commercial Spam"),
                ],
                max_length=24,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="riskprofile",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("blocked", "Blocked"),
                ],
                default="low",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="riskprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("flagged", "Flagged"),
                    ("rate_limited", "Rate Limited"),
                    ("suspended", "Suspended"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=24,
            ),
        ),
    ]
