# Generated by Django 5.2.5 on 2025-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatekeeper", "0002_remove_abuseeventtype_severity_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abuseeventtype",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="riskprofile",
            name="risk_level",
        ),
        migrations.AlterField(
            model_name="riskprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("flagged", "Flagged"),
                    ("suspended", "Suspended"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=24,
            ),
        ),
    ]
