# Generated by Django 5.2.5 on 2025-08-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatekeeper", "0003_remove_abuseeventtype_risk_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abuseevent",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="abuseevent",
            name="sms_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
