# Generated by Django 5.2.5 on 2025-08-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatekeeper", "0004_abuseevent_context_alter_abuseevent_sms_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abuseevent",
            name="message_content",
        ),
        migrations.AlterField(
            model_name="abuseevent",
            name="event_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="gatekeeper.abuseeventtype",
            ),
        ),
        migrations.AlterField(
            model_name="abuseevent",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="gatekeeper.riskprofile",
            ),
        ),
    ]
