# Generated by Django 5.2.5 on 2025-08-15 22:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatekeeper", "0005_remove_abuseevent_message_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskProfileStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prev_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("flagged", "Flagged"),
                            ("suspended", "Suspended"),
                            ("banned", "Banned"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("flagged", "Flagged"),
                            ("suspended", "Suspended"),
                            ("banned", "Banned"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="gatekeeper.riskprofile",
                    ),
                ),
                (
                    "trigger_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gatekeeper.abuseevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile", "expires_at"],
                        name="gatekeeper__profile_28547c_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="gatekeeper__expires_31d3f1_idx"
                    ),
                ],
            },
        ),
    ]
