# Generated by Django 5.2.5 on 2025-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0006_riskprofilestatuschange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiskProfileStatusChange',
            new_name='RiskProfileAction',
        ),
        migrations.RenameIndex(
            model_name='riskprofileaction',
            new_name='gatekeeper__profile_893e2e_idx',
            old_name='gatekeeper__profile_28547c_idx',
        ),
        migrations.RenameIndex(
            model_name='riskprofileaction',
            new_name='gatekeeper__expires_dca8d7_idx',
            old_name='gatekeeper__expires_31d3f1_idx',
        ),
        migrations.AlterField(
            model_name='abuseeventtype',
            name='name',
            field=models.CharField(choices=[('malicious', 'Malicious'), ('invalid_msg_length', 'Invalid Msg Length'), ('international_number', 'International Number'), ('invalid_area_code', 'Invalid Area Code'), ('invalid_number_type', 'Invalid Number Type'), ('unresolved_msg', 'Unresolved Msg'), ('commercial_spam', 'Commercial Spam'), ('restricted_user_attempt', 'Restricted User Attempt')], max_length=24, unique=True),
        ),
    ]
