# Generated by Django 5.2.5 on 2025-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0007_rename_riskprofilestatuschange_riskprofileaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='status_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RiskProfileAction',
        ),
    ]
