# Generated by Django 5.2.5 on 2025-08-19 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0008_riskprofile_status_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfileAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('suspended', 'Suspended'), ('banned', 'Banned')], max_length=24)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('suspended', 'Suspended'), ('banned', 'Banned')], max_length=24)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='gatekeeper.riskprofile')),
                ('trigger_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatekeeper.abuseevent')),
            ],
        ),
    ]
