# Generated by Django 5.2.5 on 2025-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0009_riskprofileaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskprofileaction',
            options={'ordering': ['-effective_at']},
        ),
        migrations.RemoveField(
            model_name='riskprofileaction',
            name='created_by',
        ),
        migrations.AddField(
            model_name='riskprofileaction',
            name='source',
            field=models.CharField(choices=[('preflight', 'Preflight'), ('postflight', 'Post Analysis'), ('manual', 'Manual'), ('auto_expire', 'Auto Expire')], default='preflight', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abuseevent',
            name='source',
            field=models.CharField(choices=[('preflight', 'Preflight'), ('postflight', 'Post Analysis')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='riskprofileaction',
            index=models.Index(fields=['profile', '-effective_at'], name='gatekeeper__profile_2d19d5_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprofileaction',
            index=models.Index(fields=['new_status', 'effective_at'], name='gatekeeper__new_sta_8f3eee_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprofileaction',
            index=models.Index(fields=['trigger_event'], name='gatekeeper__trigger_5b89da_idx'),
        ),
    ]
