# Generated by Django 5.2.5 on 2025-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0010_alter_riskprofileaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskprofileaction',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='riskprofileaction',
            name='gatekeeper__profile_2d19d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskprofileaction',
            name='gatekeeper__new_sta_8f3eee_idx',
        ),
        migrations.RenameField(
            model_name='riskprofile',
            old_name='status_expires_at',
            new_name='expiry',
        ),
        migrations.RemoveField(
            model_name='riskprofileaction',
            name='effective_at',
        ),
        migrations.AddIndex(
            model_name='riskprofileaction',
            index=models.Index(fields=['profile', '-created'], name='gatekeeper__profile_be2b98_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprofileaction',
            index=models.Index(fields=['new_status', 'created'], name='gatekeeper__new_sta_f43051_idx'),
        ),
    ]
